name: CI

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: update apt
        run: sudo apt-get update
      - name: install packages
        run: sudo apt-get install -yq build-essential curl autoconf pkg-config
      - name: build a deb package
        run: make all build
