name: CI

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: update apt
        run: sudo apt-get update
      - name: install packages
        run: sudo apt-get install -yq build-essential curl autoconf pkg-config
      - name: build a deb package
        run: make all build
      - uses: actions/upload-artifact@v2
        with:
          name: i3blocks deb package
          path: i3blocks_1.5-1_amd64.deb
