name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: update apt
        run: sudo apt-get update
      - name: install packages
        run: sudo apt-get install -yq build-essential curl autoconf pkg-config checkinstall
      - name: build a deb package
        run: make all build
      - name: upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            i3blocks_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
